name: notification_handler
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  cached_network_image: ^3.4.1
  sqflite: ^2.0.0+4
  path: ^1.8.0
  device_apps: ^2.2.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_notification_listener: 
    path:
      ./plugins/flutter_notification_listener-1.3.4/
  get_it: ^8.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  talker_bloc_logger: ^4.9.3
  talker_flutter: ^4.9.3
  telephony: ^0.2.0

dev_dependencies:
  build_runner: ^2.4.7
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
